package:
  name: php
  version: 8.4.1
  epoch: 1
  description: "the PHP programming language"
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: PHP-3.01
  dependencies:
    runtime:
      - libxml2

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - libxml2-dev
      - curl-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.php.net/distributions/php-${{package.version}}.tar.gz
      expected-sha256: c3d1ce4157463ea43004289c01172deb54ce9c5894d8722f4e805461bf9feaec
  - name: Configure
    runs: |
      ./configure \
        --prefix=${{targets.destdir}} \
        --enable-cli \
        --with-curl \
        --with-openssl \
        --with-readline \
        --with-zlib

  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: php-dev
    description: PHP 8.3 development headers
    pipeline:
      - uses: split/dev
  - name: php-cgi
    description: PHP 8.3 CGI
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/bin/php-cgi ${{targets.subpkgdir}}/usr/bin/
  - name: php-dbg
    description: Interactive PHP Debugger
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/bin/phpdbg ${{targets.subpkgdir}}/usr/bin/