package:
  name: composer
  version: 2.8.3
  epoch: 1
  description: "the PHP package manager"
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - php
      - git

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
      - '@local /work/packages'
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
      - busybox
      - php@local

pipeline:
  - uses: fetch
    with:
      uri: https://getcomposer.org/download/${{package.version}}/composer.phar
      expected-sha256: 8323b4105c6e166d47c9db93209370083f9e421743636e108c37d8c1126386ef
      extract: "false"

  - name: Install Composer
    runs: |
      set -x
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      mkdir -p "${EXEC_DIR}"
      mv composer.phar "${EXEC_DIR}/composer"
      chmod +x "${EXEC_DIR}/composer"
